### ISSUE TITLE
docker.te:296:ERROR 'syntax error' at token 'systemd_dbus_chat_machined' on line 1434

### ISSUE THREAD

**Issue by vanloswang** [projectatomic/docker-selinux#12]
Error info is in https://github.com/fedora-cloud/docker-selinux/issues/17.
get source code at http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/d/docker-1.11-6.git69e6294.fc25.src.rpm and compile it, then it report such an error.

**Comment by vanloswang** [comment]
Additionally, Host OS is fedora 21, and I replace docker-selinux within http://dl.fedoraproject.org/pub/fedora/linux/updates/21/SRPMS/d/docker-io-1.8.2-2.gitcb216be.fc21.src.rpm, no such an error report.

**Comment by rhatdan** [comment]
Please update to a supported fedora.  (23 or later.)
